name: Dhaba-WhatsApp-Bot

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 */5 * * *'   # Every 5 hours (keeps things awake)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Start Dhaba Bot
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npm start
